サンプルアプリ UI実装
iikeda-cq/HotpepperApiApp pull request #1
Opened 2021-04-03 08:18 UTC by iikeda-cq

## 概要
サンプルアプリのUI部分を実装しました。
FRで使っている技術や自分で使ってみたいと思った技術を取り入れて作成してみました。
アプリの機能については[README.md](https://github.com/iikeda-cq/HotpepperApiApp/tree/feature/UI#readme)にかいています。

## スクリーンショット

## 保留・レビューして欲しい箇所
- UIではRealmに店舗名や価格なども登録していますが、店舗IDがあればAPIでデータ取得できるので、API実装時に店舗IDのみ登録する実装に修正予定です。
- API実装時に`DataBinding`を使って書いてみようと思っています。
- ViewPagerやRecyclerViewでの画面遷移の書き方についてもっといい書き方があれば教えていただきたいです。（現在は`adapter`にlistenerを持たせて実装しています。）
- collectionやスコープ関数の使い方が正しいか。

2021-04-13 09:27 UTC, hyoshimi-cq requested changes
結構厳しめにレビューしました！
この段階で以下の2つは検討してもいいかなと思います！

- Realmのクライアント的なものを作成する
  - add, list, delete辺りがある
  - それをActivity, Fragment側で持つようにする
- `Store` の他に `StoreModel` のようなデータクラスを作成する
  - Clean Architectureにするのであればモデルを作成することになるため
  - Realmのクラスなので現状だと使い勝手が悪そう
  - ついでに`Store` -> `StoreModel` に変換するクラスを作成する（いわゆるMapper）

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MapsFragment.kt
> +                        lastLocation = locationResult.lastLocation
どちらでもいいんだけど、let使った方がいいかなー
```kt
locationResult?.lastLocation?.let { lastLocation ->
  ...
}
```

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MapsFragment.kt
> +    private fun storeMapping() {
動詞から〜

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/StoreWebViewFragment.kt
> +                val maxId = realm.where<Store>().max("id")
maxではあるんだけど意味合いとしてはcurrentかな 🤔

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/res/layout/fragment_store_web_view.xml
> +        <com.google.android.material.floatingactionbutton.FloatingActionButton
これ2つあるよりも画像を切り替えた方が良さそうではない？

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/StoreWebViewFragment.kt
> +            .distinct("storeId")
storeIdを指定して最初の1つ取るようなクエリがありそう 🙄

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/StoreWebViewFragment.kt
> +        realmResults.map {
`map` と `forEach` の使い分けは考えた方がいいね
 `map` は `List<T>` -> `List<R>` に変換する時で、
 `forEach` はそのリストを回したい時。

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
これだけdata binding使ってない？
使うのであれば全てのレイアウトで使おう

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
`ConstraintLayout` の中で `match_parent` は禁止です
からくりのpr-templatesにあるので確認しましょう 🙏

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/res/layout/cell_store.xml
> +        android:layout_height="250dp">
これは微妙かなー
確認している端末だとうまく表示されるのかもしれないけど、他の端末だと表示が崩れそう 😓 
どういう感じのセルにしたいです？

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/res/layout/pager_store.xml
> +            name="viewModel"
`viewModel` 🤔

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/IntExt.kt
> +    fun Int.actionBarColorToStatusBarColor(): Int {
この色を定義しておいたらそれで十分な気がするな 🤔

2021-04-13 09:27 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MainActivity.kt
> +        val actionBarColor = Color.parseColor("#FF018786")
R.color.hogeで取得して使うようにできない？

2021-05-06 04:55 UTC, iikeda-cq commented on app/build.gradle
> +    implementation 'com.google.android.gms:play-services-maps:17.0.0'
パッケージや機能ごとにまとめました！

2021-05-06 04:55 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/FavoriteStoreFragment.kt
> +    private var dataSet: MutableList<Store> = ArrayList()
valに修正しました

2021-05-06 04:58 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/FragmentExt.kt
> +        fragmentManager.popBackStack()
ボトムナビゲーションでフラグメント を切り替える際に、前のフラグメントを残したくないため追加しています

2021-05-06 04:58 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MapsFragment.kt
> +    private val dataSet: List<Store> = StoreListFragment().createTestData()
そうですね。。。
`companion`に入れるようにしました！

2021-05-06 05:00 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/StoreListFragment.kt
> +                storeId = i.toString()
Storeクラスがdata classではなかったため、このように書いていました。
しかし、StoreModelに置き換えたためご指摘いただいたように修正しました！

2021-05-06 05:01 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MapsFragment.kt
> +            childFragmentManager.findFragmentById(R.id.fragment_map) as SupportMapFragment?
そうなのですね！知らなかったです、ありがとうございます！

2021-05-06 05:01 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MapsFragment.kt
> +            ) == PackageManager.PERMISSION_GRANTED
MapExtを作成しました！

2021-05-06 05:06 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MapsFragment.kt
> +        } else {
全く同じコードなのですが、ここの分岐は
1.初めて許可を求める場合
2.以前に拒否されていた場合
の二つの場合があるので必要みたいです。（許可ダイアログの表示が若干異なるみたいです）

参考にした本にこのようにあったのであまり深く理解できていないです。。

2021-05-06 05:06 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MapsFragment.kt
> +                        lastLocation = locationResult.lastLocation
修正しました

2021-05-06 05:07 UTC, iikeda-cq commented on app/src/main/res/layout/fragment_store_web_view.xml
> +        <com.google.android.material.floatingactionbutton.FloatingActionButton
```
android:src="@{isFab ? @drawable/ic_baseline_delete_forever_24 : @drawable/ic_baseline_favorite_border_24}"
```
で切り替えるようにしました！

2021-05-06 05:08 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/StoreWebViewFragment.kt
> +            .distinct("storeId")
`findFirst()`に修正しました！

2021-05-06 05:09 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/StoreWebViewFragment.kt
> +        realmResults.map {
そうですね、若干曖昧で使ってしまっていました。
こちら全体的に見直し修正しました:bow:

2021-05-06 05:12 UTC, iikeda-cq commented on app/src/main/res/layout/cell_store.xml
> +        android:layout_height="250dp">
画像のようなGrid表示で２列で表示したいって考えています。
この場合ってどのように書いたらいいのでしょうか？

<img src="https://user-images.githubusercontent.com/66987330/117244946-e963c000-ae74-11eb-8922-6b6fe5183f1b.jpg" width=30%>

2021-05-06 05:12 UTC, iikeda-cq commented on app/src/main/res/layout/pager_store.xml
> +            name="viewModel"
dataBindingを使おうとした時の消し忘れです:bow:

2021-05-06 05:13 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/MainActivity.kt
> +        val actionBarColor = Color.parseColor("#FF018786")
こちらやってみたのですがうまくできませんでした。

2021-05-06 05:14 UTC, iikeda-cq commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
すみません、全体的に見直しました！

2021-05-06 05:17 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/FavoriteStoreFragment.kt
> +            data.genre = store.genre
```
stores.forEach { store ->
            dataSet.add(store)
        }
```
に修正しました！

2021-05-06 05:19 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/FavoriteStoreFragment.kt
> +        dataSet.clear()
```
private fun fetchRealmData() {
        val stores = fetchStores(realm)

        dataSet.clear()

        stores.forEach { store ->
            dataSet.add(store)
        }
    }
```

関数内をこのように直したのですがあっていますか？

2021-05-06 05:25 UTC, iikeda-cq commented
お忙しいところ細かく見てくださりありがとうございます！！
> - Realmのクライアント的なものを作成する
> - Store の他に StoreModel のようなデータクラスを作成する

こちらのご指摘も修正しましたのでご確認お願いします:bow:

2021-05-31 08:39 UTC, hyoshimi-cq requested changes
いくつかコメントしてます！

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/RealmClient.kt
> +    fun addStore(realm: Realm, storeId: String, name: String, url: String, price: String) {
https://qiita.com/tsumuchan/items/c5e926a96229a92c1f06
realmのインスタンスを渡すのではなく `use` 使う方がいいかも

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/FavoriteStoreFragment.kt
> +import com.google.codelab.hotpepperapiapp.StoreMapper.Companion.transform
どこの関数かわからなくなるのでimportはクラス名だけにしておきましょう
RealmClientも同様です

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/MainActivity.kt
> +    private val mOnNavigationItemSelectedListener =
`m` 🙄 
プロジェクト全体で合わせるのが基本なので削除したい
コピペは悪くないけど、きちんと揃えたり必要に合わせて修正したいです

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/MainActivity.kt
> +        this.window.statusBarColor = actionBarColor.actionBarColorToStatusBarColor()
これstyleで設定できないかな

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ext/FragmentExt.kt
> +object FragmentExt {
こういうobjectはあまり作らないですね。
ファイル名は `FragmentExt.kt` でいいんですけど、関数をそのまま書いていって大丈夫です。

それとFragmentのextensionにはなっていなくJavaのUtilsクラスみたいになってます。
なので `fun Fragment.hoge()` という書き方で、
```kt
fun Fragment.showFragment(fragment: Fragment) {
    supportFragmentManager.popBackStack()
    supportFragmentManager.beginTransaction()
        .setCustomAnimations(android.R.anim.fade_in, android.R.anim.fade_out)
        .replace(R.id.frameLayout, fragment)
        .commit()
}
```
このように書きましょうか。

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/res/layout/cell_store.xml
> +        android:layout_height="250dp">
ここのwidthをmatch、heightをwrapにするだけではダメです？

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ext/FragmentExt.kt
> +        fragmentManager.popBackStack()
このアプリでしか使えないような気がする。。。
rootに戻ってfragmentを表示する、みたいな処理があるといいな

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ext/MapExt.kt
> +    fun checkPermission(context: Context): Boolean {
`checkSelfPermission()` に合わせたと思うんですが、返り値のことを考えると `hasPermission()` がいいと思います。
もっと言うとロケーションに限っているので `hasLocationPermission()` がいいかな

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ext/MapExt.kt
> +            )
> 全く同じコードなのですが、ここの分岐は
> 1.初めて許可を求める場合
> 2.以前に拒否されていた場合
> の二つの場合があるので必要みたいです。（許可ダイアログの表示が若干異なるみたいです）
> 
> 参考にした本にこのようにあったのであまり深く理解できていないです。。

うーん、これよく分からないです 😓 
同じことをしているのであれば分ける必要はないはずです
違うことをしたいがために参考にした本では分けてるんだと思います 🤔

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/PagerStoreAdapter.kt
> +    interface ListListener {
kotlinでlistenerのためにinterfaceはあまり使わないかな
コンストラクタの引数に関数を追加した方がいいかもですね

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/PagerStoreAdapter.kt
> +class PagerViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
Bindingを渡してRecyclerView.ViewHolderにはrootを渡すようにはできない？

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/res/layout/cell_store.xml
> +            android:layout_width="match_parent"
match!

2021-05-31 08:39 UTC, hyoshimi-cq commented on app/src/main/res/layout/fragment_store_web_view.xml
> +    <FrameLayout
このFrameLayoutいる？

2021-06-13 05:50 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/RealmClient.kt
> +    fun addStore(realm: Realm, storeId: String, name: String, url: String, price: String) {
useを使うとclose()が不要になること知らなかったです。
修正しました！

2021-06-13 05:51 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/MainActivity.kt
> +    private val mOnNavigationItemSelectedListener =
すみません、気がつかなかったです。
修正しました:bow:

2021-06-13 05:52 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/MainActivity.kt
> +        this.window.statusBarColor = actionBarColor.actionBarColorToStatusBarColor()
僕の勘違いで、`color`で定義できました、失礼しました。
以下のように修正しています。
```
val actionBarColor = getColor(R.color.actionBar)
this.window.statusBarColor = actionBarColor.actionBarColorToStatusBarColor()
```

2021-06-13 05:54 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/PagerStoreAdapter.kt
> +    interface ListListener {
なるほどです。引数に関数を持たせる形で修正しました！

2021-06-13 05:54 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/PagerStoreAdapter.kt
> +class PagerViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
`root`を渡す書き方に修正しました！

2021-06-13 05:55 UTC, iikeda-cq commented on app/src/main/res/layout/fragment_store_web_view.xml
> +    <FrameLayout
不要のため削除しました

2021-06-13 05:59 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ext/FragmentExt.kt
> +        fragmentManager.popBackStack()
> rootに戻ってfragmentを表示する

こちらイメージがわかなかったので、以下のように修正しました。
- Fragmentのstackがない時はMainActivityを`finish()`する
- BottomNavigationBarの同じタブを複数回押しても、1つしかFragmentを表示しない

2021-06-19 02:36 UTC, hyoshimi-cq approved these changes
良さそう 👍

2021-06-19 02:36 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ext/IntExt.kt
> +fun Int.actionBarColorToStatusBarColor(): Int {
使ってないのであれば削除で 🙏

2021-06-27 03:32 UTC, iikeda-cq commented
@hyoshimi-cq 
ありがとうございます！！
マージします:bow:

2021-06-27 03:39 UTC, merged