サンプルアプリ API実装
iikeda-cq/HotpepperApiApp pull request #3
Opened 2021-06-27 03:41 UTC by iikeda-cq

2021-07-11 08:45 UTC, hkuwabara-cq reviewed
レベル高すぎてびっくりです。とても勉強になりました。
理解できてない部分もあり、分かる範囲でコメントさせていただきました🙏

2021-07-11 08:45 UTC, hkuwabara-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/MapsFragment.kt
> +import androidx.lifecycle.ViewModelProviders
消し忘れですかね？

2021-07-11 08:45 UTC, hkuwabara-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/LocalData.kt
> +    fun fetchFavoriteStore(storeId: String): Boolean {
名前だけ見ると、お気に入りのStoreを取得するメソッドだと勘違いしちゃうような。。
判定するみたいなニュアンスの名前がついてるといいのかなと思いました。

2021-07-11 08:45 UTC, hkuwabara-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/LocalData.kt
> +        return realm.fetchStores()
このコメントってどういう意味ですかね？
これだけrealm.closeしてないように見えるのですが問題ない感じです？

2021-07-11 08:45 UTC, hkuwabara-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/Signal.kt
> +object Signal
理解不足で教えて頂きたいのですが、Completableで値が必要ないときにSignalを渡す感じですか？？

2021-07-11 08:49 UTC, hkuwabara-cq commented
文字が被ってしまうときがあるようです。
<img src="https://user-images.githubusercontent.com/72906152/125188777-04d1b980-e270-11eb-9001-935a2a06e8f5.jpg" width=300px>

2021-07-11 08:51 UTC, hkuwabara-cq commented
自分の端末(Oppo Android10)ではマップが表示されませんでした。認証エラー？

<img src="https://user-images.githubusercontent.com/72906152/125188848-54b08080-e270-11eb-9417-78b30a5aee3f.jpg" width=300px>

![スクリーンショット 2021-07-11 16 13 19](https://user-images.githubusercontent.com/72906152/125188851-58440780-e270-11eb-8b68-02c45b06d047.png)

2021-07-13 12:22 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/RemoteData.kt
> +    }
なるほどです。修正しました！

2021-07-13 12:23 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ext/ContextExt.kt
> +        .setPositiveButton(R.string.ok) { _, _ ->
知らなかったです。。
直しました:eyes:

2021-07-13 12:23 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/MapsFragment.kt
> +import androidx.lifecycle.ViewModelProviders
そうですね、全体的に不要なimportを見直しました

2021-07-13 12:24 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/LocalData.kt
> +    fun fetchFavoriteStore(storeId: String): Boolean {
`hasFavoriteStore`に修正しています！

2021-07-13 12:26 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/LocalData.kt
> +        return realm.fetchStores()
dagger使うと同じrealmのインスタンスを参照してしまい、2回目以降Realmを呼び出すとクラッシュしてしまっていたのでそのログを貼ってました。（コメント説明不足でした。。。）
ただ、realmは都度`Realm.getInstance()`する形でいいみたいなので修正しています。

2021-07-13 12:28 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/Signal.kt
> +object Signal
そうですね。特に値を渡さないでViewに通知するためにSignalを定義しています！

2021-07-13 12:33 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/usecase/StoreListUseCaseImpl.kt
> +    }
ケースバイケースではあるみたいですが、今回は設計の勉強も兼ねているので、viewModelとusecaseが1対1で対応するように書きたかったため別々で書いています:eyes:

2021-07-13 12:37 UTC, iikeda-cq commented
> 自分の端末(Oppo Android10)ではマップが表示されませんでした。認証エラー？

個人的に気になって調べただけなので試さなくて大丈夫ですが、これが原因かなって思いました:thinking:
```
Steps:
- to ensure that device has Google Play services APK
- to install Google Play Service rev. more than 2
```
https://stackoverflow.com/questions/13696620/google-maps-android-api-v2-authorization-failure

2021-07-14 11:13 UTC, hkuwabara-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/usecase/StoreListUseCaseImpl.kt
> +    }
なるほど。承知です！

2021-07-14 11:14 UTC, hkuwabara-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/Signal.kt
> +object Signal
そうなんですね。ありがとうございます！

2021-07-15 08:10 UTC, hkuwabara-cq commented
送っていただいたAPKファイルからインストールしたらマップ表示されました！
クローンビルドだとダメみたいですね。

2021-07-15 08:11 UTC, hkuwabara-cq approved these changes
approveします！勉強になりました！

2021-07-27 07:24 UTC, hyoshimi-cq reviewed
一旦コメント 🙏

2021-07-27 07:24 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ApiClient.kt
> +object ApiClient {
これはApiClientではなくModule

2021-07-27 07:24 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/SearchDataManagerImpl.kt
> +        return Single.just(local.fetchLocalStoreIds())
`Single.fromAction {  }` みたいなものを使いたい

2021-07-27 07:24 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/usecase/FavoriteStoresUseCaseImpl.kt
> +    override fun fetchFavoriteStores(storeIdList: List<StoreModel>) {
```kt
private val favoriteIds = mutableList<String>()
private var currentStoresCount: Int = 0


fun fetchFavoriteStores(forceRefresh: Boolean)  {
  if forceRefresh {
    favoriteIds.clear()
  }

  if favoriteIds.isEmpty {
    dataManager.fetchLocalStoreIds()
      .subscribe {
        favoriteIds.addAll(it.nap { id })
        fetchStores()
      }
  } else {
    val ids = favoriteIds.subList(currentStoresCount, currentStoresCount+20)
    fetchStores(ids)
  }
}

private fun fetchStores(ids: List<String>) {
  dataManager.fetchFavoriteStores(ids)
    .subscribe {
      responseTotalPages.onNext(it.body()?.results?.totalPages)
      currentStoresCount = it.body()?.results?.totalPages.count
    }
}
```

2021-08-12 00:02 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/LocalData.kt
> +class LocalData @Inject constructor(private val realm: Realm) {
realmをinjectしないとinitエラーが発生してしまったため、`class LocalData @Inject constructor(realm: Realm)`
に修正しています。
```
java.lang.IllegalStateException: Call `Realm.init(Context)` before calling this method.
```

2021-08-12 00:02 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/ApiClient.kt
> +object ApiClient {
修正しました！

2021-08-12 00:03 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/SearchDataManagerImpl.kt
> +        return Single.just(local.fetchLocalStoreIds())
`fromCallable`を使うようにしました！

2021-08-12 00:03 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/usecase/FavoriteStoresUseCaseImpl.kt
> +    override fun fetchFavoriteStores(storeIdList: List<StoreModel>) {
こちら、参考に修正しました。ありがとうございます:raising_hand:

2021-08-12 00:05 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/usecase/FavoriteStoresUseCaseImpl.kt
> +        storeIds.subList(currentStoresCount, nextListCount).forEach { storeId ->
修正しました！

2021-08-12 00:05 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/usecase/FavoriteStoresUseCaseImpl.kt
> +                    createStoreIdQuery(favoriteIds)?.let { fetchStores(it) }
こちらlet不要になったので削除しました

2021-08-12 00:51 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/CurrentLatLng.kt
> +object CurrentLatLng {
> RepositoryとかでBehaviorSubject・Cacheとして持っておいてRepositoryに毎回リクエストする

この方針で実装しました！ありがとうございます:bow:

2021-08-17 00:41 UTC, iikeda-cq commented
@hyoshimi-cq 
レビューありがとうございます！
お忙しいところすみませんが、再度ご確認お願いします:bow:

2021-09-05 08:46 UTC, hyoshimi-cq requested changes
コメントしました！
状態管理をFragmentでやっていることが多いのでVMに移せるといいですね

2021-09-05 08:46 UTC, hyoshimi-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/usecase/FavoriteStoresUseCaseImpl.kt
> +        val nextListCount = if (min(storeIds.size - currentStoresCount, LIMIT) > 0) {
`storeIds.size - currentStoresCount` がマイナスになることがあるのかな 🤔 
```kt
val nextListCount = min(storeIds.size - currentStoresCount, LIMIT)
```
でいけるかなと思った

2021-09-15 00:14 UTC, ike04 commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/LocalData.kt
> +class LocalData @Inject constructor(realm: Realm) {
realmの設定をAppでやるように修正したことで削除できました！

2021-09-15 00:16 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/data/LocalData.kt
> +class LocalData @Inject constructor(realm: Realm) {
Appに移すことで削除できました！

2021-09-15 00:17 UTC, iikeda-cq commented on app/src/main/java/com/google/codelab/hotpepperapiapp/view/StoreListFragment.kt
> +    private var startPage = 1
見逃していました。ViewModelに移しました！

2021-09-28 07:42 UTC, hyoshimi-cq approved these changes
LGTM 👍

2021-10-02 07:06 UTC, merged